### ISSUE TITLE
Headless requires a proper path to be set, not None

### ISSUE THREAD

**Issue by yo-my-bard** [SummitPublicSchools/ducttape#5]
https://github.com/SummitPublicSchools/ducttape/blob/00e30a3803b528ff179f6d61eb834b53f2153524/ducttape/utils.py#L228

Was playing around with Headless option for DriverBuilder. Passing in only `headless=True` for a task that did not need to download anything (i.e. leaving  `download_location` in `get_driver()` as None) raises an error because the `downloadPath` parameter needs a valid path.

One solution might be:
```python
if headless and not download_location:
    tempdir = tempfile.mkdtemp()
....
#delete tempdir after driver.execute() in line 229
```

**Comment by yo-my-bard** [comment]
This part of the codebase was deleted, not sure if it's still an issue with this brave new world of Chrome 83 but I'm closing this issue for now.

**Comment by mryoho** [comment]
Haha, yeah we no longer need hacky stuff for headless now.
